# Generated by Django 4.0.5 on 2022-08-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_model_delete_top_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
