# Generated by Django 4.0.5 on 2022-08-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_model_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product_model',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
