# Generated by Django 4.0.5 on 2022-11-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_model_description_product_model_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
